/**
 * Centralized product configuration
 * Single source of truth for all product data across the application
 */

export interface Product {
  id: string;
  name: string;
  category: 'Vegetables' | 'Fruits' | 'Greens' | 'Microgreens' | 'Grocery' | 'Animal Products';
  basePrice: number;
  unit: 'kg' | 'bundles' | 'pieces' | 'liter' | 'dozen' | 'box';
  demand: 'Low' | 'Medium' | 'High' | 'Very High';
  season: string;
  imageUrl: string;
  priceChange: string; // e.g., '+5%'
  emoji?: string; // For calculator display
}

/**
 * All products available for buyback
 * Organized by category with consistent pricing and demand levels
 * Update prices here and they'll be consistent across the entire app
 */
export const PRODUCTS: Product[] = [
  // ─── VEGETABLES ──────────────────────────────────────────
  {
    id: 'oyster-mushroom',
    name: 'Oyster Mushroom',
    category: 'Vegetables',
    basePrice: 198,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1571771019784-3ff35f4f4277?w=400&q=80',
    priceChange: '+12%',
    emoji: '🍄',
  },
  {
    id: 'button-mushroom',
    name: 'Button Mushroom',
    category: 'Vegetables',
    basePrice: 220,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct–Mar',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍄',
  },
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'Vegetables',
    basePrice: 42,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1546470427-e26264b8094f?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍅',
  },
  {
    id: 'potato',
    name: 'Potato',
    category: 'Vegetables',
    basePrice: 18,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1596533129557-41bc4b73ae8f?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥔',
  },
  {
    id: 'onion',
    name: 'Onion',
    category: 'Vegetables',
    basePrice: 35,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80',
    priceChange: '+3%',
    emoji: '🧅',
  },
  {
    id: 'garlic',
    name: 'Garlic',
    category: 'Vegetables',
    basePrice: 85,
    unit: 'kg',
    demand: 'High',
    season: 'Oct-Jun',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+6%',
    emoji: '🧄',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    category: 'Vegetables',
    basePrice: 38,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1584622666223-620f9ff37f3f?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥕',
  },
  {
    id: 'bell-pepper',
    name: 'Bell Pepper',
    category: 'Vegetables',
    basePrice: 55,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+5%',
    emoji: '🫑',
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'Vegetables',
    basePrice: 65,
    unit: 'kg',
    demand: 'Medium',
    season: 'Nov-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1584398335197-c58a2c2ce941?w=400&q=80',
    priceChange: '+4%',
    emoji: '🥦',
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    category: 'Vegetables',
    basePrice: 48,
    unit: 'kg',
    demand: 'High',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1590693298496-a5388f671c90?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥦',
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    category: 'Vegetables',
    basePrice: 22,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥬',
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    category: 'Vegetables',
    basePrice: 28,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400&q=80',
    priceChange: '+5%',
    emoji: '🥒',
  },
  {
    id: 'lady-finger',
    name: 'Lady Finger (Okra)',
    category: 'Vegetables',
    basePrice: 45,
    unit: 'kg',
    demand: 'High',
    season: 'Mar-Nov',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🌿',
  },
  {
    id: 'bottle-gourd',
    name: 'Bottle Gourd',
    category: 'Vegetables',
    basePrice: 18,
    unit: 'kg',
    demand: 'Medium',
    season: 'Mar-Nov',
    imageUrl: 'https://images.unsplash.com/photo-1590693298496-a5388f671c90?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
  },
  {
    id: 'ridge-gourd',
    name: 'Ridge Gourd',
    category: 'Vegetables',
    basePrice: 20,
    unit: 'kg',
    demand: 'Medium',
    season: 'Jun-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
  },
  {
    id: 'bitter-gourd',
    name: 'Bitter Gourd',
    category: 'Vegetables',
    basePrice: 35,
    unit: 'kg',
    demand: 'Medium',
    season: 'Jun-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌿',
  },
  {
    id: 'beans',
    name: 'Beans',
    category: 'Vegetables',
    basePrice: 42,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌿',
  },
  {
    id: 'peas',
    name: 'Peas',
    category: 'Vegetables',
    basePrice: 48,
    unit: 'kg',
    demand: 'High',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🌿',
  },
  {
    id: 'corn',
    name: 'Corn (Sweet)',
    category: 'Vegetables',
    basePrice: 32,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌽',
  },
  {
    id: 'radish',
    name: 'Radish',
    category: 'Vegetables',
    basePrice: 25,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct-Feb',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
  },
  {
    id: 'eggplant',
    name: 'Eggplant (Brinjal)',
    category: 'Vegetables',
    basePrice: 38,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍆',
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    category: 'Vegetables',
    basePrice: 52,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🌿',
  },

  // ─── FRUITS ──────────────────────────────────────────
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruits',
    basePrice: 32,
    unit: 'bundles',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1528558618666-85a50bb3f114?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍌',
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruits',
    basePrice: 95,
    unit: 'kg',
    demand: 'High',
    season: 'Aug-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1560806674-104bd0691e16?w=400&q=80',
    priceChange: '+5%',
    emoji: '🍎',
  },
  {
    id: 'orange',
    name: 'Orange',
    category: 'Fruits',
    basePrice: 48,
    unit: 'kg',
    demand: 'High',
    season: 'Nov-May',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍊',
  },
  {
    id: 'mango',
    name: 'Mango',
    category: 'Fruits',
    basePrice: 65,
    unit: 'kg',
    demand: 'Very High',
    season: 'Mar-Jun',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
    priceChange: '+8%',
    emoji: '🥭',
  },
  {
    id: 'grapes',
    name: 'Grapes',
    category: 'Fruits',
    basePrice: 75,
    unit: 'kg',
    demand: 'High',
    season: 'Aug-Dec',
    imageUrl: 'https://images.unsplash.com/photo-1576515160559-06e7f4deba39?w=400&q=80',
    priceChange: '+6%',
    emoji: '🍇',
  },
  {
    id: 'papaya',
    name: 'Papaya',
    category: 'Fruits',
    basePrice: 42,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1590379278330-da6aa3baea71?w=400&q=80',
    priceChange: '+3%',
    emoji: '🧡',
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    category: 'Fruits',
    basePrice: 38,
    unit: 'pieces',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍍',
  },
  {
    id: 'guava',
    name: 'Guava',
    category: 'Fruits',
    basePrice: 35,
    unit: 'kg',
    demand: 'Medium',
    season: 'Aug-Oct',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🍈',
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'Fruits',
    basePrice: 28,
    unit: 'pieces',
    demand: 'Very High',
    season: 'Apr-Sep',
    imageUrl: 'https://images.unsplash.com/photo-1582979309284-3ee36dcb63fa?w=400&q=80',
    priceChange: '+5%',
    emoji: '🍉',
  },
  {
    id: 'mosambi',
    name: 'Mosambi (Sweet Orange)',
    category: 'Fruits',
    basePrice: 45,
    unit: 'kg',
    demand: 'High',
    season: 'Dec-May',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍊',
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate',
    category: 'Fruits',
    basePrice: 85,
    unit: 'kg',
    demand: 'High',
    season: 'Aug-Dec',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+6%',
    emoji: '🍒',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    category: 'Fruits',
    basePrice: 185,
    unit: 'kg',
    demand: 'High',
    season: 'Jan-Apr',
    imageUrl: 'https://images.unsplash.com/photo-1464454709131-ffd692591ee5?w=400&q=80',
    priceChange: '+7%',
    emoji: '🍓',
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    category: 'Fruits',
    basePrice: 245,
    unit: 'kg',
    demand: 'Medium',
    season: 'Mar-May',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+8%',
    emoji: '🫐',
  },
  {
    id: 'kiwi',
    name: 'Kiwi',
    category: 'Fruits',
    basePrice: 155,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct-Dec',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+5%',
    emoji: '🥝',
  },
  {
    id: 'coconut',
    name: 'Coconut',
    category: 'Fruits',
    basePrice: 28,
    unit: 'pieces',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥥',
  },

  // ─── GREENS ──────────────────────────────────────────
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'Greens',
    basePrice: 35,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥬',
  },
  {
    id: 'kale',
    name: 'Kale',
    category: 'Greens',
    basePrice: 52,
    unit: 'bundles',
    demand: 'Medium',
    season: 'Nov-Feb',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥬',
  },
  {
    id: 'arugula',
    name: 'Arugula (Rocket)',
    category: 'Greens',
    basePrice: 65,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🥬',
  },
  {
    id: 'parsley',
    name: 'Parsley',
    category: 'Greens',
    basePrice: 55,
    unit: 'bundles',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
  },
  {
    id: 'cilantro',
    name: 'Cilantro (Coriander)',
    category: 'Greens',
    basePrice: 35,
    unit: 'bundles',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🌿',
  },
  {
    id: 'mint',
    name: 'Mint',
    category: 'Greens',
    basePrice: 45,
    unit: 'bundles',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
  },
  {
    id: 'dill',
    name: 'Dill',
    category: 'Greens',
    basePrice: 48,
    unit: 'bundles',
    demand: 'Medium',
    season: 'Oct-Feb',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    category: 'Greens',
    basePrice: 38,
    unit: 'kg',
    demand: 'High',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥬',
  },
  {
    id: 'swiss-chard',
    name: 'Swiss Chard',
    category: 'Greens',
    basePrice: 42,
    unit: 'kg',
    demand: 'Medium',
    season: 'Oct-Mar',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🥬',
  },
  {
    id: 'fenugreek',
    name: 'Fenugreek (Methi)',
    category: 'Greens',
    basePrice: 28,
    unit: 'bundles',
    demand: 'High',
    season: 'Oct-Feb',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🌿',
  },

  // ─── MICROGREENS ──────────────────────────────────────────
  {
    id: 'microgreens',
    name: 'Mixed Microgreens',
    category: 'Microgreens',
    basePrice: 289,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    priceChange: '+8%',
    emoji: '🌱',
  },
  {
    id: 'broccoli-microgreens',
    name: 'Broccoli Microgreens',
    category: 'Microgreens',
    basePrice: 285,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    priceChange: '+7%',
    emoji: '🌱',
  },
  {
    id: 'radish-microgreens',
    name: 'Radish Microgreens',
    category: 'Microgreens',
    basePrice: 265,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    priceChange: '+6%',
    emoji: '🌱',
  },
  {
    id: 'mustard-microgreens',
    name: 'Mustard Microgreens',
    category: 'Microgreens',
    basePrice: 275,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    priceChange: '+7%',
    emoji: '🌱',
  },
  {
    id: 'alfalfa-microgreens',
    name: 'Alfalfa Microgreens',
    category: 'Microgreens',
    basePrice: 255,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    priceChange: '+5%',
    emoji: '🌱',
  },
  {
    id: 'sunflower-microgreens',
    name: 'Sunflower Microgreens',
    category: 'Microgreens',
    basePrice: 295,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    priceChange: '+8%',
    emoji: '🌱',
  },
  {
    id: 'pea-microgreens',
    name: 'Pea Microgreens',
    category: 'Microgreens',
    basePrice: 305,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    priceChange: '+9%',
    emoji: '🌱',
  },
  {
    id: 'fenugreek-microgreens',
    name: 'Fenugreek Microgreens',
    category: 'Microgreens',
    basePrice: 270,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    priceChange: '+6%',
    emoji: '🌱',
  },

  // ─── GROCERY ──────────────────────────────────────────
  {
    id: 'honey',
    name: 'Honey',
    category: 'Grocery',
    basePrice: 385,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🍯',
  },
  {
    id: 'cheese',
    name: 'Cheese',
    category: 'Grocery',
    basePrice: 425,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🧀',
  },
  {
    id: 'butter',
    name: 'Butter',
    category: 'Grocery',
    basePrice: 485,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🧈',
  },
  {
    id: 'paneer',
    name: 'Paneer',
    category: 'Grocery',
    basePrice: 395,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🧀',
  },
  {
    id: 'ghee',
    name: 'Ghee',
    category: 'Grocery',
    basePrice: 595,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🫗',
  },
  {
    id: 'coconut-oil',
    name: 'Coconut Oil',
    category: 'Grocery',
    basePrice: 285,
    unit: 'liter',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🥥',
  },
  {
    id: 'mustard-oil',
    name: 'Mustard Oil',
    category: 'Grocery',
    basePrice: 165,
    unit: 'liter',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🫗',
  },
  {
    id: 'rice',
    name: 'Rice (Basmati)',
    category: 'Grocery',
    basePrice: 85,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🍚',
  },
  {
    id: 'flour',
    name: 'Wheat Flour',
    category: 'Grocery',
    basePrice: 32,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+1%',
    emoji: '🌾',
  },
  {
    id: 'dal',
    name: 'Dal (Lentils)',
    category: 'Grocery',
    basePrice: 125,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🫘',
  },
  {
    id: 'sugar',
    name: 'Sugar',
    category: 'Grocery',
    basePrice: 42,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+1%',
    emoji: '🍬',
  },
  {
    id: 'salt',
    name: 'Salt',
    category: 'Grocery',
    basePrice: 18,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+0%',
    emoji: '🧂',
  },

  // ─── ANIMAL PRODUCTS ──────────────────────────────────────────
  {
    id: 'eggs',
    name: 'Eggs',
    category: 'Animal Products',
    basePrice: 6,
    unit: 'pieces',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥚',
  },
  {
    id: 'chicken-whole',
    name: 'Chicken (Whole)',
    category: 'Animal Products',
    basePrice: 185,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍗',
  },
  {
    id: 'chicken-pieces',
    name: 'Chicken (Pieces)',
    category: 'Animal Products',
    basePrice: 215,
    unit: 'kg',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍗',
  },
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    category: 'Animal Products',
    basePrice: 265,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍗',
  },
  {
    id: 'milk',
    name: 'Milk',
    category: 'Animal Products',
    basePrice: 52,
    unit: 'liter',
    demand: 'Very High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥛',
  },
  {
    id: 'yogurt',
    name: 'Yogurt',
    category: 'Animal Products',
    basePrice: 65,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+2%',
    emoji: '🥛',
  },
  {
    id: 'fish-tilapia',
    name: 'Fish (Tilapia)',
    category: 'Animal Products',
    basePrice: 225,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🐟',
  },
  {
    id: 'fish-rohu',
    name: 'Fish (Rohu)',
    category: 'Animal Products',
    basePrice: 285,
    unit: 'kg',
    demand: 'High',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+4%',
    emoji: '🐟',
  },
  {
    id: 'fish-catfish',
    name: 'Fish (Catfish)',
    category: 'Animal Products',
    basePrice: 265,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🐟',
  },
  {
    id: 'mutton',
    name: 'Mutton',
    category: 'Animal Products',
    basePrice: 485,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍖',
  },
  {
    id: 'goat-meat',
    name: 'Goat Meat',
    category: 'Animal Products',
    basePrice: 425,
    unit: 'kg',
    demand: 'Medium',
    season: 'Year Round',
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-9de6f3b4eca9?w=400&q=80',
    priceChange: '+3%',
    emoji: '🍖',
  },
];

/**
 * Get product by ID
 */
export const getProductById = (id: string): Product | undefined => {
  return PRODUCTS.find((p) => p.id === id);
};

/**
 * Get all product names (for dropdowns, etc.)
 */
export const getProductNames = (): string[] => {
  return PRODUCTS.map((p) => p.name);
};

/**
 * Get product price formatted with unit
 */
export const getFormattedPrice = (productId: string): string => {
  const product = getProductById(productId);
  if (!product) return '';
  return `₹${product.basePrice}/${product.unit}`;
};

/**
 * Get high demand products (for marketing)
 */
export const getHighDemandProducts = (): Product[] => {
  return PRODUCTS.filter((p) => p.demand === 'High' || p.demand === 'Very High');
};

/**
 * Get products by category
 */
export const getProductsByCategory = (
  category: Product['category']
): Product[] => {
  return PRODUCTS.filter((p) => p.category === category);
};

/**
 * Get all unique categories
 */
export const getAllCategories = (): Product['category'][] => {
  const categories = new Set(PRODUCTS.map((p) => p.category));
  return Array.from(categories);
};

/**
 * Get products by demand level
 */
export const getProductsByDemand = (demand: Product['demand']): Product[] => {
  return PRODUCTS.filter((p) => p.demand === demand);
};

/**
 * Get products in season
 */
export const getSeasonalProducts = (): Product[] => {
  return PRODUCTS.filter((p) => p.season === 'Year Round');
};

/**
 * Search products by name (case-insensitive)
 */
export const searchProducts = (query: string): Product[] => {
  const lowerQuery = query.toLowerCase();
  return PRODUCTS.filter((p) =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.category.toLowerCase().includes(lowerQuery)
  );
};
